### ISSUE TITLE
Controller: Create and code the homeRoutes.js within the controllers folder

### ISSUE THREAD

**Issue by c-phelps** [c-phelps/workout-wizardz#33]
controllers/homeRoutes.js
Create and code the homeRoutes.js file for the controllers folder
homeroutes should include
get for "/" render homepage and pass value homepage true
res.render('homepage', { homepage: true })
get for "/login"
handle logic for if user is logged in
render login if not logged in

**Comment by ftek00** [comment]
PR : https://github.com/c-phelps/workout-wizardz/pull/46

express routes for rendering the homepage with a check for user authentication, redirecting to the login page if not authenticated
