### ISSUE TITLE
View: Create a main.handlebars HTML file in the views/layouts folder

### ISSUE THREAD

**Issue by c-phelps** [c-phelps/workout-wizardz#35]
Create an handlebars HTML file for the main page that we will use, this will be the main container for the website. Have a thematic header with the name of the website and a nav bar that we can hide conditionally based on if the user is on the homepage. If the user is on the landing page/homepage the buttons should not appear in the nav.

< some html >
{{#if boolHomepage}}
<nav>buttons</nav>
{{/if}}
<more html>
    {{ body }}
< more html >

**Comment by ftek00** [comment]
PR : https://github.com/c-phelps/workout-wizardz/pull/57
